### ISSUE TITLE
Graph shows only one line

### ISSUE THREAD

**Issue by siburny** [fifonik/FFMetrics#1]
If I select one reference video file and two videos to compare to, graph only shows one of the files even though metrics are calculated for all files.

![image](https://user-images.githubusercontent.com/1232281/92606343-d286b280-f280-11ea-8233-678c7f54de02.png)

Using latest version: v0.8.1b

**Comment by fifonik** [comment]
It is very strange that there are 9 filenames in legend below the plot.
Could you advise, what FFMpeg version you use?

Could you please do the following:
- Exit the program;
- Delete file FFMetrics.log;
- Start the program with option "-log-level=DEBUG";
- Tick 'Save to CSV' and 'Log FFMpeg commands' checkboxes;
- Run;
- Send me these FFMetrics.log and csv files.

Thanks.

P.S. Have you chosen the 4k Model manually?

**Comment by siburny** [comment]
I can't seem to reproduce it anymore. If you use "Clear ALL" button to remove all files and then select them again graph doesn't remove previous files.

* 4K model was pre-selected
* ffmpeg version "git-2020-08-31-4a11a6f"

**Comment by fifonik** [comment]
Thanks. 
I see the issue with not files "Clear All" button.

**Comment by fifonik** [comment]
> 4K model was pre-selected

Could you explain what does it mean? :)

**Comment by siburny** [comment]
You are right: when I select 4K video proper model is selected.

**Comment by fifonik** [comment]
I've published version 0.8.2b where the issue with "Clear All" button is fixed.
