### ISSUE TITLE
Массовый расчёт метрик

### ISSUE THREAD

**Issue by iPaltus** [fifonik/FFMetrics#100]
Спасибо за программу!
Сейчас в окно расчёта удаётся добавить до 24 файлов. Сделайте пожалуйста возможность добавить больше файлов - перекидыванием в окна программы, либо загрузкой текстового списка файлов.

Или же возможность автоматического закрытия программы после расчёта метрик из командной строки. Сейчас после расчёта программа остаётся открытой и последующий расчёт запускает новый экземпляр.

Приходится считать VMAF для 40-50 файлов для выбора оптимальных настроек кодирования.

**Comment by fifonik** [comment]
You can further increase the maximum number of files program process in one go.
To do so you need to create configuration file (ffmetrics.conf) with desired number of series provided in it (check included ffmetrics.conf.example).

As for option to exit the program after calculation -- I will add it in further version. Thanks for suggestion.

**Comment by fifonik** [comment]
I've just published 1.4.0 beta where a new command line option "-exit" was added. 

P.S. It must be used in conjunction with "-run".
