### ISSUE TITLE
Not even simple statistics on simple h264 movie

### ISSUE THREAD

**Issue by Napolitain** [fifonik/FFMetrics#102]
Hi,

I wish I could fix the bugs, but since the source code isn't public, I can't help you.
This is a h264 file which isn't correctly computed.

![image](https://user-images.githubusercontent.com/18146363/198146627-a8c9659e-9579-423e-8b73-cb5274860376.png)

**Comment by fifonik** [comment]
Could you follow troubleshooting steps and supply log please?

**Comment by fifonik** [comment]
Cannot investigate without additional information provided. 
Sorry.
