### ISSUE TITLE
FR: Allow more than 24 files to be added

### ISSUE THREAD

**Issue by oviano** [fifonik/FFMetrics#105]
Thanks for this useful piece of software.

I wanted to analyse a set of 96 videos, but was frustrated to find that it can only do batches of 24 at a time.

Is there a particular reason for this artificial limit? Presumably it only processes one file at a time, so it can't be a memory or processing issue.

**Comment by fifonik** [comment]
I'm too lazy to add so many different styles for lines.
However, you can do it yourself -- just rename file `ffmetrics.conf.example` to `ffmetrics.conf` and define 96 line styles existing using 24 definitions from it as an example.
