### ISSUE TITLE
Types of file supported?

### ISSUE THREAD

**Issue by a-trioux** [fifonik/FFMetrics#106]
Hello great work! Thanks for this tool. 
I was just wondering what are the types of files supported now? I couldn't find the answer by myself, sorry... I can see that *.mp4 works perfectly, however the original video file is usually *.yuv, do you plan to add this in the next version? Thanks in advance for your reply!

**Comment by fifonik** [comment]
FFMetrics need to know details about video files such as frame size, frame rate, colour format (+ something else) to correctly supply arguments to ffmpeg.
If ffmpeg can get such information about your file -- it should be supported by ffmetrics as well.
By default files list limited to avi, avs, 264, h264, mts, m2ts, mkv, mov, mp4, mpeg, mpg, ts, webm, but you can always switch type while using file pickers to 'All files' or simply drag & drop it from explorer to ref/distorted files inputs.

However, raw video streams such as yuv or simirat that does not have the information required are not supported.

**Comment by kuznetcoff777** [comment]
Its a pitty that no such functionality to allow user set right info for yuv files

**Comment by presyncope** [comment]
I suggest you to use HEVC lossless encoding using ffmpeg. or you can also use constant QP encoding with low QP(10 or 12).

**Comment by fifonik** [comment]
You can also use other lossless encoders such as free HuffYUV, UTVideo, cheap MagicYUV of some that inbuilt into ffmpeg. 
They are fast and use less space on drive than raw yuv stream.
