### ISSUE TITLE
error in 0.9.0 Beta when changing files

### ISSUE THREAD

**Issue by pperquin** [fifonik/FFMetrics#11]
Hi,

Thx a lot for you great software.

In 0.9.0 Beta, i have an error not see in 0.8.7.

I change source and files to compare, click start and all goes in error.
Re starting the software solve the problem
I also see one freeze in VMAF analyse, but look at the log if there is and error, solved by restarting the software

regards,

please find the log

[FFMetrics ERRORS.log](https://github.com/fifonik/FFMetrics/files/5881839/FFMetrics.ERRORS.log)

**Comment by fifonik** [comment]
I've found an issue in 0.9.0 when mediainfo for ref is not updated when you select another ref. This might cause the issue you have.
Unfortunately, I cannot say it for sure and option for logging ffmpeg was not checked in your case. 
I will upload fixed version soon.

**Comment by pperquin** [comment]
thx a lot, i will try it

**Comment by fifonik** [comment]
Could you test version 0.9.1 that I just published?
Thanks.

**Comment by pperquin** [comment]
Hi,

I just test it and the problem seem solve.

But now it seem to have a speed bug.
in 9.0beta
psnr 45% cpu
ssim 24% cpu
vmaf 100% cpu

in 0.9.1 it seem to be half cpu usage

psnr 14% cpu
ssim 13% cpu
vmaf 47% cpu

thx a lot for the work

**Comment by fifonik** [comment]
> I just test it and the problem seem solve.

Thanks for testing.


> now it seem to have a speed bug.

This is really strange as I have not changed anything in this regards.

Could you try to follow the next steps for 0.9.0 & 0.9.1:
- Delete FFMetrics.log
- Run FFMetrics
- Tick Options | Write FFMpeg commands in log
- Add reference & distorted files
- Provide logs

P.S. ffmpeg version and ref & distorted files must be the same in both cases

**Comment by pperquin** [comment]
Hi,

I just run 0.8.7, 0.9.0 and 0.9.1 with the same ffmpeg.exe and i can confirm the speed issue(easy to see in vmaf where we goes from 100% in 0.8.7 and 0.9.0 to 49% in 0.9.1)

my processor is an amd 3945x.

I also notice than results are not the same in 0.9.1 than in 0.8.7/0.9.0

please find the files


[D.zip](https://github.com/fifonik/FFMetrics/files/5892419/D.zip)

**Comment by fifonik** [comment]
Oh, I see. Logs explain everything.
I've forgotten to disable some partially implemented features I'm working on. As a result, the 0.9.1 do some conversions.
Could you check this binary please (put it instead of 0.9.1): https://www.dropbox.com/s/vvs2woc23g9dboy/FFMetrics.zip?dl=1

**Comment by pperquin** [comment]
ok seem good for speed and results are same as old version.

Is it possible to accelerate vmaf with Cuda ?

**Comment by fifonik** [comment]
Hi,


> ok seem good for speed and results are same as old version.

Thanks for checking this out.
I will "release" the new version soon (with ffmetrics/ffmpeg versions info  
added to csv).



> Is it possible to accelerate vmaf with Cuda ?

Sorry, I do not know if this implemented in LIBVMAF at all and this is  
also accessible through ffmpeg.
If this is accessible through ffmpeg I can make changes so FFMetrics will  
supply required arguments to ffmpeg.
However, I will not be able to test it as I do not have NVIDIA GPU.


Thanks.


-- 
With best wishes,
Michael

**Comment by pperquin** [comment]
Hi,

I found something working with your command line : -hwaccel cuda (https://trac.ffmpeg.org/wiki/HWAccelIntro)

In my case it decode the video with cuda but  once again VMAF score are not the same

regards
[test.zip](https://github.com/fifonik/FFMetrics/files/5893478/test.zip)

**Comment by fifonik** [comment]
I've already investigated the -hwaccel option (checked dxva2 and d3d11va as I do not have other options).
The options does NOT speed up PSNR, SSIM & VMAF calculations.
However, I do have plans to add a new feature one day that will allow user to pass custom options to ffmpeg (it is in [TODO](https://github.com/fifonik/FFMetrics/blob/master/TODO.md)).

As for your logs: SOFTWARE -- only 113 frames were processed, while CUDA -- 1500. So the different results. In any case, fps is quite the same (check ExecFps at the end -- 51.7 vs 53.1)

**Comment by fifonik** [comment]
I've published 0.9.2 that should fix the issue and should not have the "speed" issue you mentioned.
Could you double check it please. Thanks.

**Comment by pperquin** [comment]
hi

it seem to be ok now.

thx a lot
