### ISSUE TITLE
[Solved - antivirus issue] Exception thrown at the start of beta 1.4.7b1 version of FFmetrics

### ISSUE THREAD

**Issue by jeryll7** [fifonik/FFMetrics#110]
Now I get exception thrown at the start of FFmetrics 1.4.2.b1 and 1.4.7b1:

CiceroUIWndFrame: FFMetrics.exe - Application Error : The exception unknown software exception (0xe0434352) occurred in the application at location 0x00007FFB865BCD29.

FFmetrics works after a while, so if anything it's only annoying, but should be fixed, thanks...

**Comment by fifonik** [comment]
Could you follow troubleshooting steps and provide FFMetrics.log please?
I cannot re-produce the crash on my system so I need any clues when the crash happening.

My only guess at this moment -- some components updates cause the crash (mentioned in changelog). 
I can try to build the program with previous versions of these components for you to test.

**Comment by jeryll7** [comment]
> Could you follow troubleshooting steps and provide FFMetrics.log please? I cannot re-produce the crash on my system so I need any clues when the crash happening.
[Here you go...](https://app.box.com/s/jswyvubo5r7a0savht89eva9piea8161)

**Comment by fifonik** [comment]
Wait a moment, as I see the screenshot of the program + plot this means that there were no exception. Right?
I need you to repeat the steps until you have exception. And as this is an exception, I do not need screenshots at all, just the log.

**Comment by jeryll7** [comment]
Ehm ... could you re-read my first post here?

Now, I get exception thrown **at the start** of FFmetrics...
...and also...
FFmetrics **works after a while**...
and log is where screenshot is ...

**Comment by jeryll7** [comment]
So, I finally managed to restart my PC and now FFmetrics 1.4.7b1 won't start at all with interesting popup (didn't see this one yet)
![image](https://user-images.githubusercontent.com/36567662/219935067-c82f6bf6-b77f-461d-8bb8-848b746cbf93.png)

**Comment by jeryll7** [comment]
Solved - antivirus issue, I will add exception for the FFmetrics...
