### ISSUE TITLE
how to open prebuilt vmaf json files?

### ISSUE THREAD

**Issue by nukim1** [fifonik/FFMetrics#116]
I want to open some vmaf json files on 'Plots' dialog. 
but i have no idea how to do

**Comment by fifonik** [comment]
Well, you cannot as the program does not have such functionality.

**Comment by presyncope** [comment]
ok thanks

**Comment by nukim1** [comment]
ok thanks

**Comment by SebSonic1979** [comment]
Do you plan to add this? Re-opening saved Metrics for visualization after the Program was closed would be very handy.

**Comment by fifonik** [comment]
TLTR: I do not have plans to implement this, sorry.

Full story:
With "Save results" the only per file results saved (actually appended) to csv file. No per frames metrics stored there at all.
Per frame values saved in csv files when you tick checkbox "Save frames metrics to files". However, this is simple helper that works while files are being processed. Files format inconsistent between metrics and every received field saved. The goal here --create cvs files that can be opened and used with Excel. Program is unable to open these files back.

Technically it would be possible to add functionality that will read these files back, but it would be very strange to have a loaded graph that is not related to anything that is displayed in program at the same time.

Proper implementation would require to have saves that contain all per frame metrics and make the program more complicated and harder to use. 
I'd like to avoid this.
