### ISSUE TITLE
About cropping black edges

### ISSUE THREAD

**Issue by f10555** [fifonik/FFMetrics#117]
Many source videos have top and bottom black edges, and if I crop the black edges and re-encode them, I want to be able to compare the quality of the two. How should I do this?
If there is no ready way to do this, I suggest adding the ability to compare reference videos after cropping.

**Comment by fifonik** [comment]
Unfortunately, you cannot do it in this program directly right now.

There are million of scenarios for adjusting videos: resize, crop, convert colour range/frame rate, adjust colour/sharpen/saturatio, etc + combinations.
I do not have plans to add into the simple video quality metric calculation frontend UIs for all these adjustments.
Sorry.

I understand your exact situation and it have some sense.
You can do one of the following:
- Create simple avisynth wrapper for ref with required crop and use the .avs file as a ref;
- Crop original video in your preferred video editing program, save it as lossless/uncompressed and use as a ref.

**Comment by f10555** [comment]
Thanks for the reply, I am currently using the second method and I like FFMetrics!

**Comment by f10555** [comment]
Another request, I've never used avs before, so I wonder if you could please give me a sample .avs file from which I can modify it to my own, many thanks!

**Comment by fifonik** [comment]
https://avisynthplus.readthedocs.io/en/latest/avisynthdoc/corefilters/directshowsource.html (other SourceFilters can be used, this depend on your source file)
https://avisynthplus.readthedocs.io/en/latest/avisynthdoc/corefilters/crop.html

```
DirectShowSource("ref.mp4")
Crop(offsetX, offsetY, width, heigh)
```

**Comment by f10555** [comment]
Thank you for your patience:)

I did some research and installed AviSynthPlus_3.7.2_20220317.exe.
I created a "ref.mp4" (x.264/AAC), and a "test.avs" file in the same directory.

The content of test.avs is only two lines:
DirectShowSource("ref.mp4")
Crop(0,94,1280,532)

When I dragged the ref.mp4 directly into FFMetrics, it recognized the video correctly.
But when I dragged test.avs into FFMetrics, it didn't seem to work.

Also, I tried to install the plugin and use the FFmpegSource2 filter and again it does not work.
Please forgive my complete lack of understanding of the AviSynth system, am I making some basic mistake?

Screenshots:
![20230429205145](https://user-images.githubusercontent.com/71049050/235330591-85f7b12d-3b16-4eb9-8714-e504493fa81e.png)
![20230429205403](https://user-images.githubusercontent.com/71049050/235330592-4f9d06e3-e55c-4385-af3b-4048d9c26ea5.png)

**Comment by fifonik** [comment]
I'd exclude FFMetrics for now from experiments and check if the avisynth installed correctly and your your script works.
To do this you can install some playes that support avs (MPC HC or MPC BE) and drag the script onto the player window. It should play. If not -- something not right with the avisynth installation or you script (I noticed that strange quotes used in your avs-script).

FFmetrics should work with avs:
![image](https://user-images.githubusercontent.com/7234987/235332422-556650f5-4b75-40d9-a8e7-7462146c8830.png)

**Comment by f10555** [comment]
Well, I think I understand what you mean, I will spend more time learning Avisynth, thanks again for your help!

I did check and the "strange quotes" should not be a problem, that's just the Chinese font I used in Notepad to read the Chinese content.

Have a great day bro!
