### ISSUE TITLE
[Feature request] show filesize and potentially "quality per filesize" ratio

### ISSUE THREAD

**Issue by LittleVulpix** [fifonik/FFMetrics#118]
A reasonably simple-to-implement feature - additional set of columns in the main list - sortable - with "file size" and "quality per size" so to speak.

Let's say I have one encode that has VMAF average of 90 and is 10 MB, and then I have another encode which has VMAF average of 91 and is 100MB.

Just by looking at the current screen I cannot discern that for just 1 extra quality the size has increased tenfold; which makes it a little more work to go and put this data into an excel or so to understand it from that perspective.

I think getting a filesize should be very simple, and then the "quality per size" would be a simple calculation (though I suppose you might consider adding it per selected metric, i.e. if your quality indicator is SSIM, PSNR or VMAF...).

Thank you for this epic software, it's the best tool to use when experimenting with encoding settings and different codecs!

**Comment by fifonik** [comment]
Sorry for late reply.

I agree that this is easy top implement, however I doubt that this is actually useful.

The tool is used for calculating **visual** quality metrics, but quite often in files we have video + audio(s) + subtitles so correlation between file size and video stream size is lose (BTW, the program is displaying video stream size if available).

The suggested metric score per size is even stranger beast.
I do not know how this can be used at all.
People who after quality do not care much about size. People who after size do not care much about quality. 

Imagine you have file 1 sized 2MB with quality 100 and file 2 sized 1 MB with quality 50 (just numbers, not close to reality).
For two the suggested "metric per size" values will be the same -- 50. 
To be honest -- I do not know what this means and how it might be usable for end user at all. 
To make things worse, implementing the suggestion means it would be added 4 additional columns. This make the UI more clunky and harder for use when following typical workflows.

As per above, I'm not going to implement this. Sorry.

**Comment by LittleVulpix** [comment]
No worries, thanks for considering it.
The use case here is/was specifically for people who may be re-encoding their existing library and want to find a "reasonable size for reasonable quality", and don't particularly care so much about either. I agree about the cluttered UI. Honestly just one column with filesize (or well, video stream size, if you will) would be enough; but that's fine :)
