### ISSUE TITLE
GUI Closing

### ISSUE THREAD

**Issue by jriker1** [fifonik/FFMetrics#119]
Maybe the program is dated but looks like frequently in Windows 11 when i compare to MKV files with HEVC video in them the GUI will close.  Happens fairly quick but couldn't figure out why my fans were still ramping up.  Well FFMpeg is still running in the background the GUI has just dissapeared.  Thoughts?

**Comment by fifonik** [comment]
Unfortunately, I do not have a clue.
I'd start with checking windows logs (Event Viewer).

**Comment by fifonik** [comment]
It is possible that program crashes under some circumstances.
Cannot do anything without FFMetrics.log or windows even log.
