### ISSUE TITLE
adding ffmetric and ffmpeg version to the csv files

### ISSUE THREAD

**Issue by pperquin** [fifonik/FFMetrics#12]
is it possible to add ffmetric and/or ffmpeg version to the csv files ?

regards,

**Comment by fifonik** [comment]
Should not be hard. Will do this.

**Comment by fifonik** [comment]
With version 0.9.2b that I just published FFMetrics & FFMpeg version numbers will be added in results CSV file.

**Comment by pperquin** [comment]
it work
