### ISSUE TITLE
not honoring duration settings

### ISSUE THREAD

**Issue by jriker1** [fifonik/FFMetrics#120]
Found you have beta versions if you click on the full list of compiled versions.  That said, when I set it to check 10 minutes, and say to skip the first minute, it keeps going past that duration unlike the last release version.  Currently on 44k+ frames and growing for a video with 23.976 fps.

**Comment by fifonik** [comment]
Could you follow troubleshooting steps and provide ffmpeg command line from log please?

**Comment by fifonik** [comment]
Unfortunately, I cannot help you with your issue without additional info.
