### ISSUE TITLE
FFMetrics crashes

### ISSUE THREAD

**Issue by Heporis** [fifonik/FFMetrics#121]
![image](https://github.com/fifonik/FFMetrics/assets/51895154/f1fe0771-0a34-4af2-8c97-34912214d1d7)

**Comment by fifonik** [comment]
Could you follow troubleshooting steps please?

**Comment by Heporis** [comment]
[FFMetrics.log](https://github.com/fifonik/FFMetrics/files/12268947/FFMetrics.log)
It crashes no matter where the ffmpeg locates.

**Comment by fifonik** [comment]
In your file offset spacified as 1.4 sec, but when FFMetrics getting preview image it is asking to get frame at fixed position 1 sec (-ss 1). As a result, image extraction fails.
I still do not know why FFMetrics is crashing after that and I need to find a way to re-produce the crash.

In the meantime you can try the latest beta (1.4.8): it is possible that the crash is already fixed there.
As for the correct preview image extraction offset -- I've made required changed already and it will be in the next beta.

**Comment by Heporis** [comment]
1.4.8 still crashes.

**Comment by fifonik** [comment]
How big is your video file? Can you share it (PM)?

**Comment by Heporis** [comment]
I downloaded [the video](https://drive.google.com/file/d/1VvmDPe5YDDgPX3YgoiO15sQzRa_5oHi1/view?usp=sharing) from a live stream. 
The origin format is .flv, and I convert it to .ts with ffmpeg -i input.flv -bsf:v h264_mp4toannexb -f mpegts -c copy output.ts

**Comment by fifonik** [comment]
I downloadad you file & the same ffmpeg.exe and it works with no issues in my case (checked with 1.4.8b).
To be honest -- I do not have a clue what could cause the crash.
![image](https://github.com/fifonik/FFMetrics/assets/7234987/fa451f20-dc58-453f-bfc9-14f79a5c735b)

**Comment by Heporis** [comment]
Does it needs some other system components besides .net framework 4.8? Maybe it is because I removed some system components with MSMG Tookit.

**Comment by fifonik** [comment]
To be honest -- I do not know. 
I though: as program was compiled to target 4.8, windows let you know if anything missed.

**Comment by fifonik** [comment]
I can send you executable compiled with debug info.
May be it shows additional details while crashing.

**Comment by Heporis** [comment]
Send me plz

**Comment by fifonik** [comment]
Here you are (please let me know when you download it, I'll delete the file):
[FFMetrics.1.4.9b.debug.zip](https://github.com/fifonik/FFMetrics/files/12285448/FFMetrics.1.4.9b.debug.zip)

**Comment by Heporis** [comment]
downloaded
Thank you!

**Comment by fifonik** [comment]
Have you got chance to try it yet?

**Comment by Heporis** [comment]
Today, I restarted my computer, and it works well. idkw. Maybe it's a system issue. 
Thank you so much!
