### ISSUE TITLE
sorting columns issue

### ISSUE THREAD

**Issue by PhilippeR** [fifonik/FFMetrics#124]
When you sort the columns by clicking on their headers, the check box column is not sorted. 
After sorting, if you click on a checkbox, it is the initial file that is affected and not the one you think you are acting on.

**Comment by fifonik** [comment]
Thanks. Will check it out.

**Comment by fifonik** [comment]
I've reproduced the issue and found what causing it.
However, I do not know how to fix it correctly at this time as in the program it is possible to order files manually AND by ordering by clicking at the metrics' headers. This is weird...

**Comment by PhilippeR** [comment]
I forgot. V1.4.8.b

**Comment by fifonik** [comment]
Should be fixed in 1.4.9 beta 1 (could you check it please?)

**Comment by PhilippeR** [comment]
Hello,
I tried on two different pc and it's not fixed.

**Comment by fifonik** [comment]
I've made another attempt to deal with the issue.
Can send you executable for testing if you like.
Thanks.

**Comment by fifonik** [comment]
Implemented in 1.5.0 beta 1 (just released).

**Comment by PhilippeR** [comment]
I will try as soon as i can and let you now.

**Comment by PhilippeR** [comment]
I tested v1.5b2 and it seems to be fixed. Great job.

**Comment by fifonik** [comment]
> when i remove all files at the same time, app crashes.

I'm unable to re-produce it. Any details?

**Comment by fifonik** [comment]
Thanks a lot. Re-produced (I tried without calculation)

**Comment by PhilippeR** [comment]
you're welcome.

**Comment by fifonik** [comment]
I've just uploaded beta 3 with the fix.

**Comment by PhilippeR** [comment]
Fixed!
