### ISSUE TITLE
[Question] What is the meaning of the different Statistics?

### ISSUE THREAD

**Issue by ShehOmran** [fifonik/FFMetrics#128]
I can't find any place explaining the meaning of the different Stats. I am especially confused by the distinction between Avg (which is the value shown by default) and Mean put under Frames statistics. When usually in Mathematics both Average and Mean refer to the Arithmetic Mean unless specified otherwise. Sorry if I just missed an obvious things that caused my confusion.

**Comment by fifonik** [comment]
FFMpeg returning average value per file and some values per frame.
The 1st one is shown as "Avg".
All the values are under "Frames statistics" are calculated by FFMetrics based on "per frame" values returned. You can calculate it yourself if you store frames metrics into CVS file, open it in Excel and do the math.
