### ISSUE TITLE
Toggle files from graph

### ISSUE THREAD

**Issue by tormento** [fifonik/FFMetrics#129]
It would be nice to toggle file metric graphs directly from the plot window.

A click on the lower caption colors to turn off and on would be more than enough.

To be clear, here:

![image](https://github.com/fifonik/FFMetrics/assets/2351785/45cc3c0c-2d9e-4058-ba25-3fa8d8d532dc)

**Comment by fifonik** [comment]
The OxyPlot library used in the program has in-built functionality for this and it is quite easy to implement the following behaviour:
- All files displayed on plot regardless their checkboxes;
- If file's checkbox is ticked, file's line is displayed (if metric calculated);
- If file's checkbox is un-ticked, file's line is not displayed **and** file name in plot is greyed out;
- When file name clicked on plot, the file's checkbox toggled.

In other words, the file's checkbox is synced with file name on plot.
However, I do not like this behaviour as ticked file's checkbox means the file's metric will be calculated on run.

I believe it should be different options to exclude file from metric's calculation and from displaying on plot.
So, the only behaviour that make sense is:
- Un-ticking file's checkbox in main window should exclude the file from metric's calculation **and** it should completely disappear from plot (file name and line);
- Clicking on file name in plot should toggle (hide/show) the file's line and grey out the file name in plot

Unfortunately, such implementation require a lot of internal changes for such a small (imho) feature.

So, sorry, this will not be implemented.
