### ISSUE TITLE
How to show csv file in Excel as Graph

### ISSUE THREAD

**Issue by MationPlays** [fifonik/FFMetrics#133]
Hello,
I got these metrics csv files(one FFMetrics_results file and one for vmaf of each video) now and don't know how to visualize them in Excel.
I don know what these numbers even are and what the term for the coloums mean.
Please help

![ffmetrics_results_excel](https://github.com/fifonik/FFMetrics/assets/38890464/8bc0447c-5dc7-4640-9048-d6054a8b3b9d)
![framemetrics_ffmetrics_vmaf](https://github.com/fifonik/FFMetrics/assets/38890464/621c8971-f1fa-4612-a5c3-2064eb4929f2)

**Comment by fifonik** [comment]
Unfortunately, I cannot help as I do not know what exactly you doing and what you'd like to have at the end. Sorry,

**Comment by MationPlays** [comment]
Like i just want to be able to see the graph of the vmaf again in excel. There is a graph visible in ffmetrics when running it i want to able to see this again

**Comment by fifonik** [comment]
You need to import the tab delimited file/files into Excel (for some reason "Open" does not work in Excel as it is not smart enough to detect that the file is "tab delimited").
When importing you should make sure that "Tab" is selected as fields separator.
Then you will need to select "frame" column for X-values and "vmaf" column for Y-values while creating line chart. 
Unfortunately, I cannot provide exact steps as I do not have Excel (can provide steps for LibreOffice Calc if you need).

**Comment by MationPlays** [comment]
Thanks, please tell me how to do it with libre office, i also never did this with excel

**Comment by fifonik** [comment]
Simplest line chart LibreOffice Calc: 
- Ctrl+O | select file | Open
- Make sure "separated by" - tab | OK (in my case it is selected by default, I do not know if it remember the last choice of auto-detects correct separator)
- Select "vmaf" column, that is M in my case (or any other column you'd like to use in chart as Y-Values)
- Insert | Chart
- Chart | Lines only
- Finish

I believe the question should be asked in LibreOffice community or just google.

**Comment by fifonik** [comment]
![image](https://github.com/fifonik/FFMetrics/assets/7234987/30c6cd3e-eee3-454a-a2de-6a1b0633ef7d)
