### ISSUE TITLE
repeatable crash - distorted files click+drag

### ISSUE THREAD

**Issue by joeymavity** [fifonik/FFMetrics#135]
Steps to reproduce:

1. Add a single reference file so that the reference area is valid
2. Add a single distorted file to the project
3. Click the file list item and drag to the column header

Expected behavior: Nothing happen

Actual behavior: App crashes

Version: 1.4.9b

Additional notes:

It's a weird edge case but my clumsy fingers have made it happen twice, so I thought I'd pass it along, especially since it doesn't happen in many cases. For instance, if multiple distorted files are in the list, or if no reference file is open. I hope this is helpful, it's pretty easily reproducible, though obviously a low priority.

**Comment by fifonik** [comment]
Hm. Unable to re-produce.

**Comment by joeymavity** [comment]
I thought I wasn't able to, then got it to repeat again. Let me know if I should upload a recording. 

1. Open FFMetrics
2. Start a new project (ctrl+shift+N)
3. Drag reference file to Reference 'path to file'
4. Drag two files to 'distored' area, let media info load
5. Delete one of the files (del)
6. Drag distorted file to 'distorted' area, let media info load
7. Drag distorted file to column header (sometimes I had to do this twice)

This 'feels' less perfectly repeatable today than it did last night, but I've also attached a file to help. I have such anxiety about uploading bad bug reports to projects 😅

https://github.com/fifonik/FFMetrics/assets/8808740/9776025a-1cfb-45ee-addf-1143361b7abe

**Comment by fifonik** [comment]
Thanks, I was able to re-produce it twice. 
Unfortunately, not really sure how to re-produce the issue reliable that is required to check if my code change will wix the issue. Still trying.

**Comment by fifonik** [comment]
I've made some changes and hope it fixed the issue. Can send you executable for testing if you like.

**Comment by joeymavity** [comment]
Happy to test - what's the best way?

**Comment by fifonik** [comment]
Here you are. Please let me know when you download it. Thanks.
[FFMetrics.zip](https://github.com/fifonik/FFMetrics/files/15122408/FFMetrics.zip)

**Comment by joeymavity** [comment]
Downloaded, sorry for the delay

**Comment by joeymavity** [comment]
I can't promise it's fixed - it wasn't as perfectly reproducible as initially thought - but none of my attempts have broken it so far. I included some weird dumb stuff, including multi-select, weird ordering/deleting, etc. And all seemed to be fine. I'll keep working with this version and let you know if something comes up, otherwise this seems fixed. I won't close this in case you want to tie it to code changes or something, but you obviously can feel free to.

**Comment by fifonik** [comment]
Thanks for testing. Lets keep it open for a while.

**Comment by fifonik** [comment]
The change implemented in 1.5.0 beta 1 (just released).
