### ISSUE TITLE
[Feature] add Support for n_subsample

### ISSUE THREAD

**Issue by jaschx** [fifonik/FFMetrics#136]
Hi,
it would be nice, if you can add Support for n_subsample to the Gui. (libvamf Option)
Its speeds up Processing big Times, and from my personal Testing doesent lose to much Accuracy set to 5-10 .

wbr Alex

**Comment by fifonik** [comment]
Where can I read abot the option? In FFMPEG manual it is just mentioned, I have no idea what is the range of expected values.

P.S. right now you can adjust parameters supplied to ffmpeg in FFMetrics.conf.

**Comment by fifonik** [comment]
As I see, this is just a number > 0. 1 -- every frame calculated (default), 2 -- every 2nd calculated, 3 -- every 3rd calculated and so on.
I tried without n_subsample and with 5. Based on FFMpeg output the second one was just a bit faster on my PC: 2.0x vs 1.6x. 
Is it really worth to have it in UI?

**Comment by jaschx** [comment]
It depends, on not superfast machines, like older I7s  (4core 8 Threads) u get arround 3-4x speedup with 5 for example.
Also, i use it with AV1, where decomp is slower overall.
But Thanks for looking in to this.

**Comment by fifonik** [comment]
> Also, i use it with AV1, where decomp is slower overall.

That was my point. On more advanced decoders like AV1 the decoding will take even more time so it will be smaller benefits from dropping off some frames during VMAF calculation.
However, on bigger frames it should be more benefits.

P.S. I've already implemented it before testing performance gain. So now I'm not sure if I should merge it into main branch or not.

**Comment by jaschx** [comment]
Thanks, its up to you.
On my older Maschine the Performance was going up times 4 with my 1080p Av1 Test Encode, thats why i was asking for it.
Lets say it like this, its not hurting anybody to put it in (if you already did, why not ).

and a nice Sunday from Germany

**Comment by fifonik** [comment]
Will add it into the next version.

**Comment by fifonik** [comment]
Implemented in 1.5.0 beta 1 (just released).
