### ISSUE TITLE
Does FFMetrics automatically upscale distorted video?

### ISSUE THREAD

**Issue by MationPlays** [fifonik/FFMetrics#138]
Hello,
with VMAF the resolution must be the same of reference and distorted. When calculating vmaf using ffmpeg over command-line an error occurs if the resolution is not the same. Inn FFMetrics there is no error and a vmaf-score gets calculated.
My Question is what FFmetrics is doing? Does it automatically upscale the distorted video to match the reference?
Thanks a lot!

**Comment by fifonik** [comment]
Yes, it is upscaling distorted video to ref resolution.
You cah turn on FFMpeg commands logging and check what commands it is issuing.

**Comment by MationPlays** [comment]
Thanks, I now tested it and there are the same vmaf values as using ffmpeg with scale filter

**Comment by MationPlays** [comment]
where can I see the log? Is it live logging? I found Options->"Write FFMpeg commands to log"

**Comment by fifonik** [comment]
Yes, this is the option. When ticked, you should see FFMetrics.log aside of FFMetrics.exe.

**Comment by fifonik** [comment]
![image](https://github.com/fifonik/FFMetrics/assets/7234987/f4138d67-b702-4a0a-96ee-fa59ccf90b67)
