### ISSUE TITLE
Request custom segment time for long videos

### ISSUE THREAD

**Issue by aliofwind** [fifonik/FFMetrics#14]
For long videos, full stream analysis is unrealistic, especially using vmaf, but the longest segment analysis is only 2 minutes in the preset. In most cases, 2 minutes cannot cover multiple scenes in the video, so I need longer segment to analyze. 

I request the option to add a custom segment time.

**Comment by fifonik** [comment]
I will definitely add a few items on the durations list in the next version (5, 10, 15, 20, 30 minutes).
As for "custom time" -- I will think about it, but no promises.

**Comment by fifonik** [comment]
More duration options were added into the dropdown.

**Comment by fifonik** [comment]
Sorry, no custom time.
