### ISSUE TITLE
Does FFMetrics everything that easyVmaf does?

### ISSUE THREAD

**Issue by MationPlays** [fifonik/FFMetrics#141]
Does FFMetrics apply all these filters in the ffmpeg command: The reference and distorted videos need to be frame-synchronized. The scan mode (interlaced/progressive) has to match; they have to have the same duration; they have to have the same frame-rate.
The reference and distorted videos’ resolution has to match, which often requires a robust up/down-scaling procedure.  
Thanks for any info!

**Comment by fifonik** [comment]
> The reference and distorted videos need to be frame-synchronized

FFMetrics is trying to do this.


> The scan mode (interlaced/progressive) has to match

FFMetrics do not make any changes to this so if no match -- values calculation by ffmpeg might fail (I have not even checked it).
However, imagine ref was interlaced and you deinterlaced and encoded it. 
What you expecting FFMetrics to do? Deinterlace as well? What algorithm should be used? There are many of them. When I do deinterlacing, I'm also cleaning the video from deinterlaced artifacts.
My point is -- there is no real value if a lot of processing be done under the hood.


> they have to have the same duration

No, they do not have to.


> they have to have the same frame-rate

No, they do not have to, FFMpeg can handle different frame rates. 
However, everything I mentioned above still apply here as well.


> The reference and distorted videos’ resolution has to match

FFMetrics resizes distorted to ref's frame size (you can choose scaling method in options, but it is limited to what ffmpeg offering).
However, everything I mentioned above still apply here as well.
