### ISSUE TITLE
Ffmetrics 1.52 beta2 - remove selected - does not work with 2 or more files

### ISSUE THREAD

**Issue by JamesPous** [fifonik/FFMetrics#142]
![Bug-ffmetrics](https://github.com/fifonik/FFMetrics/assets/85449576/261e0235-57a9-4bd1-afab-0cf16cffbac8)

Thank you for the latest beta release. I am happy to see ffmpeg 7.0 support.

If I have two or more files in my list and want to delete two files, the program will directly close.
I tried the remove selected button and used the delete key on my keyboard. Both do the same.
I think it is an error.

**Comment by fifonik** [comment]
Thanks. 
Already reported, fixed locally and I'm going to release fixed version later today.

**Comment by fifonik** [comment]
I've just uploaded beta 3 with the fix.

**Comment by JamesPous** [comment]
Thank you, it works fantastic.
