### ISSUE TITLE
ffmetrics 1.5.0 beta 3 - filenames get cut after resizing the columns

### ISSUE THREAD

**Issue by JamesPous** [fifonik/FFMetrics#143]
![Bug-ffmetrics](https://github.com/fifonik/FFMetrics/assets/85449576/543ea781-4da2-40d7-bcd7-d241cdc3e1c1)

I resized the columns to see the full filename.
The list of the filenames does not automatically refresh long filenames and do not show them.

**Comment by fifonik** [comment]
This is not a new bug.
Such implementation was from very beginning as it is very tricky to create a proper implementation that will calculate text's width (in characters) from available grid cell width in pixels to shorten the text (this should include all these DPI, scaling etc). 
To be honest I do not even know how to do this in reasonably optimal way. So it will not be fixed completely.
However, I've slightly tweaked my hardcoded guessing logic, so it might be better (or worse, who knows).
Will be available in the next beta version.

**Comment by fifonik** [comment]
Just uploaded beta 4 with some improvements in this area.

**Comment by JamesPous** [comment]
Great solution! Thank you!

**Comment by fifonik** [comment]
> I would first truncate the parent path before starting to truncate the filename

This is exactly how it was implemented from the beginning.
The tricky bit is to find out the max string size that is needed to make the above logic to work.

**Comment by fifonik** [comment]
Assume it is implemented :)
