### ISSUE TITLE
[feature request] ffmetrics 1.5.0 beta 4 - Showing bitrate for all files (e.g. mkv) - currently mp4 only!

### ISSUE THREAD

**Issue by JamesPous** [fifonik/FFMetrics#144]
Ffmetrics can show the video bitrate of my mp4 files in the media info.
I often test the SSIM and VMAF score to get an impression of the quality and used settings in my encoding program (e.g. Handbrake). Sometimes the SSIM or VMAF scores increase, but the video bitrate gets higher, too.
So I will compare, if you get the same or higher quality score at the same bitrate of the checked video files.

Is it possible to show the video bitrate of the calculated video files, too?
Ffmetrics does not show them for mkv files, but mp4 files work perfect.
I think the reason could be, that mp4 files store the videobitrate in their fileheader or metadata.

![feature-ffmetrics](https://github.com/fifonik/FFMetrics/assets/85449576/14b2f738-1a30-42f2-90f8-555f993e1597)

**Comment by fifonik** [comment]
All the media info is getting from ffmpeg's output. 
FFMpeg can report bitrate for file (so all streams are taken into consideration) and per stream (this is what we usually need as we comparing video quality and it might be many audio streams that are also could be quite big)
Unfortunately, for mkv it is not always reporting bitrate per stream. Sometimes it is not reporting at all and sometimes it is reportad in metadata that ffmetrics is not parting yet.
So no bitrate from ffmpeg -- no bitrate in UI.
The bitrate you see for ref is marked with asterisk (*), this mean this is FILE bitrate, bot STREAM bitrate.
You still see the FILE bitrate (also with asterisk) for distorted files in tooltip -- just hover mouse over file's mediainfo and wait a bit.

I think I can try to parse metadata that will help for some files.

**Comment by fifonik** [comment]
Added stream's metadata parsing into beta 5.
