### ISSUE TITLE
[feature request] Double click on filename open the video file in default video player

### ISSUE THREAD

**Issue by JamesPous** [fifonik/FFMetrics#145]
Sometimes I want to see the video files again to check the visual quality with my eyes.
So it would be perfect, if you can open the video file with a double click on the path- und filename.
Then the windows sytem default video player should open and play the file.
If it is easier to develop, a customized video player (e.g. VLC Player, MPC-BE, MPC-HE, etc.) should open the video file for playback.

**Comment by fifonik** [comment]
Added "Play" buttons for distorted files in beta 5 that will start player associated with the file's extension.

**Comment by JamesPous** [comment]
Fantastic! The play button is a very good solution and self explaining.
