### ISSUE TITLE
v1.5.0 beta 5 stuck at "Assigning program options"

### ISSUE THREAD

**Issue by BillyBob1354** [fifonik/FFMetrics#146]
I open FFMetrics and it gets stuck at "Assigning program options"

When it is like this most of the buttons are grayed out and can not do anything.

*1.5.0 beta 4 works

![Screenshot 2024-05-13 043610](https://github.com/fifonik/FFMetrics/assets/46253676/ae7e66e6-5897-4efe-9b9d-b3e417d57e33)

**Comment by BillyBob1354** [comment]
Beta 6 fixes the issue, thanks.

**Comment by fifonik** [comment]
Nah, this was just a test. Proper fix for the issue is coming %-)
