### ISSUE TITLE
[Feature Request] Add more (explicit) options to the "Skip" dropdown

### ISSUE THREAD

**Issue by Hlsgs** [fifonik/FFMetrics#147]
I am aware that there are feature requests opened requesting custom values and whatnot. However, as far as I'm concearned, adding some more values to go "deeper" into the files would suffice and should be trivial to implement. The adjacent "Duration" dropdown already has 12 values, so I don't see why "Skip" would not accomodate as many from a UI standpoint.

I would proppose adding:

- 5 minutes
- 10 minutes
- 15 minutes
- 30 minutes
- 45 minutes
- 1 hour

Thank you for this great tool!

**Comment by fifonik** [comment]
Technically, it is very easy to add new options into the dropdown.

However, if you tried to use Skip you should notice that it is slow.
For proper calculation frames should not be skipped and this means that ALL fo them decode (even the one that before skip time).
The large the selected skip value, the longer the delay.
This is the reason I do not want to add large values into the Skip.
Sorry.

**Comment by fifonik** [comment]
There is an option -accurate... in ffmpeg that I used before. Not any longer as it is unreliable. Using trim atm (you can check logging and look what options passed to ffmpeg).

> isn't ffmeg smart enought

It is not posible in general at all as keyframe intervals are not fixed.

**Comment by fifonik** [comment]
I will do a few more tests to make a decision.

**Comment by fifonik** [comment]
Yes, it is.

**Comment by fifonik** [comment]
Added more items in the Skip dropdown in 1.5.0 beta 8 (it is slow)
