### ISSUE TITLE
Wrong Values in FFMetrics v1.5b7

### ISSUE THREAD

**Issue by alikalhor77** [fifonik/FFMetrics#148]
Hi These three values are incorrect on the latest version of the software. I compared them to v1.4.9b that I used previously.
![FFMetrics](https://github.com/fifonik/FFMetrics/assets/151856807/4a551a4f-76e4-4b01-9a76-d6315a77e1e2)

**Comment by fifonik** [comment]
The issue re-produced. Thanks.

**Comment by fifonik** [comment]
Should be fixed in 1.5.0 beta 8 (just uploaded)

**Comment by fifonik** [comment]
Have you got chance to check it out?
