### ISSUE TITLE
Extract frames png inaccurate color

### ISSUE THREAD

**Issue by antatura** [fifonik/FFMetrics#149]
Suggestion:
    -vf scale=in_color_matrix=bt709:flags=accurate_rnd+full_chroma_int+bitexact,format=rgb24

**Comment by tormento** [comment]
I found that bug too.

**Comment by fifonik** [comment]
Thanks for your suggestion.
Adding `-pix_fmt rgb24 -sws_flags accurate_rnd+full_chroma_int+bitexact`
Will be available in the next published version.
I believe the `in_color_matrix` should not be added as input streams might be very different. I will let ffmpeg to decide.

**Comment by fifonik** [comment]
Inplemented in 1.5.0 beta 12.
