### ISSUE TITLE
0.9.3b - Start button greyed out 

### ISSUE THREAD

**Issue by CJAnti** [fifonik/FFMetrics#15]
I found your great tool today, but can't use it.
The "Start" button is not clickable and that doesn't change, whatever I do.
I've put ffmpeg.exe into the program folder and the progam recognizes that it's there (as seen on the screenshot).
Also I tried this with different reference and distorted files, but "Start" still doens't become clickable.
What might be the issue?
![image](https://user-images.githubusercontent.com/5544871/107634059-42063100-6c69-11eb-8345-c57913dbee36.png)

**Comment by matteocontrini** [comment]
@CJAnti select the metrics that you want to compute in the last 3 columns 😉

**Comment by fifonik** [comment]
Yes, you have to "tick" at least one metric.

P.S. All 3 should be ticked by default on first run. I will double check.

**Comment by CJAnti** [comment]
Thanks, that does the trick.
Seems to be a small detail that i missed, since it is not very intuitive and/or clear to see that you need to check the columns.
Apart from that, those were unchecked from the start.
I just downloaded a few of the previous releases and the last one, where those checkboxes were ticked is 0.8.7b.

**Comment by fifonik** [comment]
Thanks for checking it out.
I'll fix it in the following version.

**Comment by CJAnti** [comment]
Issue wasn't an issue, but is fixed.
I'm glad I could help as well.
Stay healthy!
