### ISSUE TITLE
Add turbo-metrics support

### ISSUE THREAD

**Issue by tormento** [fifonik/FFMetrics#165]
Please, evaluate adding [turbo-metrics](https://github.com/Gui-Yom/turbo-metrics) when using CUDA compatible video cards.

**Comment by fifonik** [comment]
Unfortunately, this is simply not possible at this moment as I do not have hardware that can be used for this (Nvidia GPU)

**Comment by fifonik** [comment]
I checked it out. It is not inbuilt in ffmpeg so will not add it into ffmetrics.
