### ISSUE TITLE
App crashes regularly if computer is under heavy load

### ISSUE THREAD

**Issue by lashchev** [fifonik/FFMetrics#19]
If I have heavy transcoding going on in the background - the app always crashes. Based on the logs, I guess it crashes when it tries to load media info, and ffmpeg communication times out.

**Comment by fifonik** [comment]
Possible.
However, the program only gets media info at the very beginning, before calculation process started.
If it crashes after, the reason is different. I hope it is already fixed in my version (that I'm going to release soon).

**Comment by lashchev** [comment]
It crashes in these case:
1. When I add files to the project too quickly
2. When I open it, it starts loading the old project but meanwhile, I remove files from the project
3. If I add files to the project, but in the background, I have FFmpeg doing some transcoding

**Comment by fifonik** [comment]
Thanks for details. Will investigate.

**Comment by fifonik** [comment]
Timeout increased from 2 to 5 seconds in version 0.9.4b. I hope it will be better now.

**Comment by fifonik** [comment]
Have you got chance to test is it better now?
