### ISSUE TITLE
VMAF score does not show correct decimal delimiter in locale with delimiter other than point

### ISSUE THREAD

**Issue by matthiasduyck** [fifonik/FFMetrics#2]
For some reason the VMAF score in the file list is missing a decimal delimiter(point/comma), the other scores are OK though. When hovering however, I do see a delimiter. A clew might be that the VMAF uses a comma in the hover tool-tip, while the others use a point. I'm also seeing this in the CSV export.

![image](https://user-images.githubusercontent.com/10989584/93516803-d2468100-f92a-11ea-83db-83ba98e00a2e.png)
![image](https://user-images.githubusercontent.com/10989584/93516941-028e1f80-f92b-11ea-8d78-635d37113519.png)

Could be related: the graphs for VMAF seem to be broken as well, probably due to this decimal delimiter issue:
![image](https://user-images.githubusercontent.com/10989584/93517011-22254800-f92b-11ea-99d8-8945ae07aa50.png)

The other graphs work perfectly as expected.

An important note and a probable cause: I'm not on an EN-US version of windows. I'm in a NL-BE locale, where we use a comma(,) as the decimal delimiter. I'm guessing the software/code somewhere expects the point instead of the system locale value. I don't know what language the app is written in, but you should be able to get the delimiter that is in use from the system.
**Edit: I quickly tested this theory by setting my decimal delimiter in windows to point instead of comma and this fixes/hides the issue.**

Offtopic: great little app, very useful!

**Comment by fifonik** [comment]
Thanks for your report and investigation.

I have not checked personally what delimiters ffmpeg uses for reqults.
It looks like the ffmpeg's behaviour is not consistent and locale depended.

I'll try to add a workaround.

**Comment by fifonik** [comment]
Could you try this executable please:
https://www.dropbox.com/s/yu731cwfkq1n86e/FFMetrics.zip?dl=1

**Comment by matthiasduyck** [comment]
> Could you try this executable please:
> https://www.dropbox.com/s/yu731cwfkq1n86e/FFMetrics.zip?dl=1

This new executable seems to solve the issue!
Once again, great work work on the app!

**Comment by fifonik** [comment]
Thanks for checking it out. 
I published version 0.8.2 where the issue is fixed.
