### ISSUE TITLE
Taskbar app button should show project progress

### ISSUE THREAD

**Issue by lashchev** [fifonik/FFMetrics#20]
It would be nice if the taskbar shows that the project analysis is running.
AFAIK it can be done with [TaskbarItemInfo.ProgressState](https://docs.microsoft.com/en-us/dotnet/api/system.windows.shell.taskbariteminfo.progressstate?view=netframework-4.7.2)

**Comment by fifonik** [comment]
Thanks for suggestion.
Will try to implement it in further version.

**Comment by fifonik** [comment]
Implemented in version 0.9.4b

**Comment by fifonik** [comment]
Have you got chance to test it yet?
