### ISSUE TITLE
can calculate vmaf

### ISSUE THREAD

**Issue by 4h4h270** [fifonik/FFMetrics#24]
Its used to be work good, after I update to newest version it always fail to calculate vmaf, but SSIM & PSNR is fine.

here's the log

2021-03-21 05:52:51	ffmpeg.exe -hide_banner -nostdin -i C:/Tools/x265-Yuuki/1.mp4 -i C:/Tools/x265-Yuuki/abs-189-C.mp4_1.mp4 -lavfi [0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf='eof_action=endall:n_threads=23:phone_model=0:pool=mean:model_path=C\:/Tools/FFMetrics/vmaf-models/vmaf_v0.6.1.pkl:log_fmt=json:log_path=C\:/Users/nanoh/AppData/Local/Temp/FFMetrics/d680ea91-61c7-4703-a264-bce065df5fc7.log' -f null -
2021-03-21 05:52:51	ERROR: C:\Tools\x265-Yuuki\1.mp4: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:/Tools/x265-Yuuki/1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isom
    creation_time   : 2021-03-21T09:00:02.000000Z
  Duration: 00:03:20.23, start: 0.000000, bitrate: 1187 kb/s
    Stream #0:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv), 720x404, 1185 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2021-03-21T09:00:02.000000Z
      handler_name    : L-SMASH Video Media Handler
      encoder         : HEVC Coding
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:/Tools/x265-Yuuki/abs-189-C.mp4_1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isom
    creation_time   : 2021-03-21T09:04:11.000000Z
  Duration: 00:03:20.23, start: 0.000000, bitrate: 7605 kb/s
    Stream #1:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv), 720x404 [SAR 1:1 DAR 180:101], 7602 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2021-03-21T09:04:11.000000Z
      handler_name    : L-SMASH Video Media Handler
      encoder         : HEVC Coding
Stream mapping:
  Stream #0:0 (hevc) -> settb
  Stream #1:0 (hevc) -> settb
  libvmaf -> Stream #0:0 (wrapped_avframe)
libvmaf INFO `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
Output #0, null, to 'pipe:':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isom
    encoder         : Lavf58.45.100
    Stream #0:0: Video: wrapped_avframe, yuv420p10le, 720x404, q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 wrapped_avframe
libvmaf WARNING could not read model from path: "C:/Tools/FFMetrics/vmaf-models/vmaf_v0.6.1.pkl"
libvmaf WARNING pkl model files have been deprecated, use json
libvmaf ERROR problem loading model file: C:/Tools/FFMetrics/vmaf-models/vmaf_v0.6.1.pkl
[Parsed_libvmaf_4 @ 0000027ca20a2bc0] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
Conversion failed!

**Comment by fifonik** [comment]
FFMpeg you use does not support pkl models. 
So delete or move them from vmaf-models dir and use json models instead.

**Comment by 4h4h270** [comment]
Thx alot, problem solved
