### ISSUE TITLE
Collect 1st, 5th, 10th and 25th percentiles for the metrics

### ISSUE THREAD

**Issue by lashchev** [fifonik/FFMetrics#25]
Average numbers are quite misleading when it comes to real-world metric comparisons. When you want to keep an eye on the encoding quality - you need to pay attention to the number of "bad frames" (frames with the lowest scores). Collecting lower percentiles would help to understand the quality of the worst frames/sequences.

**Comment by fifonik** [comment]
I'm implementing 5, 10 & 25 percentiles. 
Thanks for the suggestion.

**Comment by fifonik** [comment]
Implemented in 0.9.8
