### ISSUE TITLE
Save "bad frames" for the further review

### ISSUE THREAD

**Issue by lashchev** [fifonik/FFMetrics#26]
"Bad frames" can be defined as the lowest 1st percentile of a selected metric. For example, if the test sequence has 1000 frames and you use VMAF - "bad frames" would be 10 frames with the lowest VMAF score.

Usually, you would want to review the bad frames visually to understand the quality drops.
Based on the review, you can improve the transcoding or enhancement settings.

Saving at least the list of bad frames would allow us to extract them with FFmpeg later.
But, ideally, bad frames themselves should be saved as well (original and distorted) together with the video analysis CSV report.

**Comment by fifonik** [comment]
5 bad frames could be extracted since 0.9.5b.

**Comment by mirh** [comment]
Would it be also possible to save together the original reference frames?
Not all codecs/players play nice with "go to frame" commands.

**Comment by fifonik** [comment]
I like this idea. Added in my todo list
