### ISSUE TITLE
Please Include Bitrate (and possibly file size) in File Information List

### ISSUE THREAD

**Issue by Nagorak** [fifonik/FFMetrics#31]
It would really be helpful if bitrate (and possibly file size) was listed along with the various metrics scores for the files. Seeing that one file scored better isn't that useful in isolation without also knowing the bitrate, since higher bitrate obviously results in higher quality output. In order to judge the tradeoffs in compression you really need to see both parameters, but right now the only way to view bitrate is by hovering over the file, which takes a second to show up, and is a hassle when comparing multiple files.

**Comment by fifonik** [comment]
Bitrate is added in short media info in 0.9.6.
I do not think that file size should be added there.
