### ISSUE TITLE
progress is not shown

### ISSUE THREAD

**Issue by JustinWebDev** [fifonik/FFMetrics#34]
I set my ref video and a distorted video, start the analysis for full stream, the CPU and GPU kick up, I get the green curve, but no progress bar or red curve, even after 5min.  I can't interact with the dialog.  I have to kill the app with Task Mgr.

v0.9.6b on W10 v20H2 x64, Ryzen 7, 64GB RAM, Quadro P400

**Comment by fifonik** [comment]
Green/red curve? What do you mean?
If you only add one ref and one distorted, it should be only one graph.
Still, you still should be able to interact with the app.

Could you do the following:
- Close the app
- Delete FFMetrics.log
- Start app with option -log-level=debug
- Repeat your steps
- Take screenshot (Alt+PrnScr of Win+Shift+S)
- Supply the screenshot and the log.

Thanks.

**Comment by JustinWebDev** [comment]
Sorry - I don't any longer have the files I was seeing the problem with, and a similar test with different files is not reproducing.  At the time, I did not realize the problem may be specific to certain files.  My apologies.
