### ISSUE TITLE
Aplication crash without error when click on Extrac bad frames

### ISSUE THREAD

**Issue by Blaztix** [fifonik/FFMetrics#52]
Aplication crash without error when click on <kbd>Extrac bad frames</kbd>

FFMetric Versión: v0.9.7b
Windows 10 Home 19043.1081

Original file: 
- MKV 1920x1080-23-,98p yuv420p10le (tv), Bitrate: 8662 kb/s*, Duration: 00:23:56.13 (1.44GB)

3 files to analyze:  _differents config in ffmpeg_

- MKV 1080p, YUV420, TV (620MB)
- MKV 1080p, YUV420, TV (107 MB)
- MKV 1080p, YUV420, TV (210 MB)

**Comment by fifonik** [comment]
Unfortunately, I do not have any idea about the issue yet.
Could you try the following:
- Close the program
- Delete FFMetrics.log
- Run it with option -log-level=debug
- Repeat your steps
- Supply FFMetrics.log

**Comment by fifonik** [comment]
I've found a few ways to crash the program:
- Add ref file + 2 distorted files
- Tick first file and PSNR
- Calc
- Untick first file + tick the second one (or untick PSNR + tick SSIM)
- Extract => crash

Going to fix that in the next version. 
However, if your case is different I will need more details.

**Comment by Blaztix** [comment]
Thanks for reply, I think the video file are not relevant. Or all my video files are strange or version of ffmpeg.

[FFMetrics.log](https://github.com/fifonik/FFMetrics/files/6773547/FFMetrics.log)

**Comment by fifonik** [comment]
> 2021-07-06 21:06:39	DEBUG: FF.ExecStatus.Started, -hide_banner -accurate_seek -ss 20,1834862385321 -i D:\path\to\crf.mkv -frames:v 1 -f image2 C:\path\to\Temp\6f24683e-75b7-40e9-9d01-31e7c61ed7d3.png
> ...
> 2021-07-06 21:06:40	DEBUG: FF.ExecStatus.StdErr: **Invalid duration specification for ss: 20,1834862385321**

Regional settings were used internally to build duration and they have comma as a decimal separator.
Will fix it.

**Comment by fifonik** [comment]
Should be fixed in 0.9.8

**Comment by Blaztix** [comment]
Fixed!

**Comment by fifonik** [comment]
Thanks for checking.
