### ISSUE TITLE
[Question] What do the colors mean?

### ISSUE THREAD

**Issue by fu-hsi** [fifonik/FFMetrics#53]
Green, red and transparent when displaying statistics, VMAF for example?

**Comment by fifonik** [comment]
Green -- the best statistic of the metric within ticked & processed files
Red -- the worst statistic of the metric within ticked & processed files

Example:
Here I calculated PSNR & SSIM for 1 & 3 files. 
When I hover mouse over PSNR value of the 1st file I see that all stats except  StdDev are the best.
![image](https://user-images.githubusercontent.com/7234987/125142270-aff04f00-e15a-11eb-9f84-dd1ab49f73ca.png)

When I hove mouse over PSNR value of the 2nd file I see that all values except StdDev are the worse
![image](https://user-images.githubusercontent.com/7234987/125142501-402e9400-e15b-11eb-9b2c-6598389a240a.png)

**Comment by fifonik** [comment]
Should be fixed in 0.9.8

**Comment by fu-hsi** [comment]
So which file is better?
For me (for a simple man :) first file with the highest PSNR value, or not?
Can you consider change background item in list view for the best match to the original file?
In this case, you wouldn't need to read the statistics.
Maybe some sort by column will be good option too.
Now we don;t have sort posibility by the best and worst match.

**Comment by fifonik** [comment]
There is no just "better". Different people have different criteria.
In most cases, it should be enough just to check the displayed value/graphs and not go to the stats.
Higher PSNR/SSIM/VMAF value => "better". Not always, this is the reason why the program exists.

As for highlighting the best/the worst in the grid -- please create a new "issue" for the feature request.

**Comment by fu-hsi** [comment]
Graph is OK, but when i have 15 items it's hard to read graph when several files (lines) overlap.
Sorting is a good option.
Gratings.
