### ISSUE TITLE
Unable to push "Start" button

### ISSUE THREAD

**Issue by ntusenkonstnar** [fifonik/FFMetrics#59]
Probably not an issue but my own fault - however I do not see what is wrong. 
Previously I got a text saying "FFMpeg timeout" in the buttom left corner. 
Now that has changed to:"FFMpeg: 2021-07-06git-758-full_build-www.gyan.dev (supported PSNR, SSIM). 
VMAF does not seem to work and as far as I can read that would be another separate issue. However it is impossible to push "start" no matter  how I pick all other settings. I have addes both reference file and 3 other files but I still can not start any analyze. The path to ffmpeg is added to the system path. 

Any idea of what I'äm doing wrong here? 

BR/Erik

**Comment by fifonik** [comment]
Have you selected at least one metric?
Could you provide a screenshot?
Have you tried to follow troubleshooting steps that are on the main page?

**Comment by ntusenkonstnar** [comment]
Hi and thank’s for your answer!

I can not check any of the boxes (I want to choose the VMAF but non of the boxes can be checked). Is there any config-file I need to work with for selecting metric? 

Attached is a screenshot, I do not know why it is ”back” to “FFMpeg: Timed out” in the lower left corner again instead of the other text that was seen there yesterday. If I open an ordinary command prompt and write ffmpeg the ffmpeg starts regardless of which folder I’m in so the path is correctly added. 

 

I have also looked at suggested actions regarding Common issues “start button disabled”. FFMPEG should be found. Both reference and distorted files are added but metrics can’t be selected. 

 

Any idea of how to proceed? 

 

BR/Erik

**Comment by fifonik** [comment]
I do not see any screenshots.
In any case, if "Timed out" is shown instead of FFMpeg version, the program will not be able to do anything as it was not able to successfully get information from FFMpeg.
I can only recommend to re-read Troubleshooting section and provide info that mentioned there.

You can try to download static ffmpeg version from FFMpeg download page and unpack it directly into the FFMetrics' program folder.

**Comment by fifonik** [comment]
I will try to increase timeout for version and ffmpeg features detection calls.
In a meantime you can try to use shared ffmpeg builds, they are usually a bit faster on startup (dlls cached by OS).

**Comment by fifonik** [comment]
Timeout increased in 0.9.9b. Could you check if this helped with your issue please?

**Comment by ntusenkonstnar** [comment]
Hi, I'm out in the Archipelago with no computer currently but will give it
a try as soon as I'm back home.

BR/Fredrik

Den tors 29 juli 2021 kl 09:07 skrev fifonik ***@***.***>:

**Comment by ntusenkonstnar** [comment]
Sorry for a late answer. I have been extremely busy at work and not been able to test until now. I can confirm that your last version works as expected since the adjustment of the time-out setting. 

 

Thanks a lot!! 

 

BR/Fredrik

**Comment by ntusenkonstnar** [comment]
Hi, 

The app runs fine now on the computer where I first installed it. However, when doing the same installation (same downloaded version of FFMPEG and same download of FFMetrics (1.0.0) it turns out that in the other computer “VMAF” is greyed out. 

As mentioned it is the exact same installation package that I use on the other computer where VMAF works and the same installation package for FFMetrics also that has a vmaf-models folder that contains the exactly same file. 

 

Any idea what could cause the VMAF to be greyed out on one computer? 

 

BR/Fredrik

**Comment by ntusenkonstnar** [comment]
Sorry for not putting it together I one mail. I forgot to tell that FFMetrics.log actually says: “WARNING: VMAF metric initialization failed”. 

 

BR/Fredrik

**Comment by fifonik** [comment]
I'd prefer you create another ticket for this new issue.
In a meantime you can try to follow troubleshooting steps as on the project main page and check similar ussies that some other people had (#57, #29).
Thanks.
