### ISSUE TITLE
[Feature] Add option to set start time for analyze

### ISSUE THREAD

**Issue by Blaztix** [fifonik/FFMetrics#61]
In the options menu, you can set a scan time, [FULL, 5-10-20-30 seconds, 1-2-5-10-10-15-20-30 minutes]. Great! A very useful option, but always analyze from the beginning of the video.

Yes I want to do a quick 10 second analysis, but my video has 15 seconds of black scene with voice. This is useless.

If I could be configured to analyze 0:02:00 to 0:02:10, for example. That would be great!

![image](https://user-images.githubusercontent.com/4962591/126369140-878805d3-e567-4d2d-829c-427cdbf51958.png)

For example:
![image](https://user-images.githubusercontent.com/4962591/126371201-2d683145-8fa4-48ea-bd57-905564b856fb.png)

Or with a text input.

**Comment by fifonik** [comment]
Thanks for the suggestion, I will try to add it in the next version.

**Comment by fifonik** [comment]
Implemented in 0.9.9b
