### ISSUE TITLE
Can't click any buttons. FFmpeg timed out?

### ISSUE THREAD

**Issue by Katzenwerfer** [fifonik/FFMetrics#63]
Hello,
I have an issue where I can't click any buttons in the interface
![image](https://user-images.githubusercontent.com/53267697/127441581-91eef1c2-a7ca-42fc-b3c2-839560406da0.png)
This seems to only happen with certain builds (I think ones compiled with VMAF or something)
The ones I have had the issue with are from
- [gyan.dev](https://www.gyan.dev/ffmpeg/builds/) latest git build
- [jeremylee.sh](https://jeremylee.sh/bin.html) latest release
- [Hybrid](https://www.selur.de/)'s embedded ffmpeg build

Only one that seems to work well is from [BtbN](https://github.com/BtbN/FFmpeg-Builds)'s builds, but those ones aren't built with VMAF compatibility
I'll attach the [log](https://github.com/fifonik/FFMetrics/files/6898368/FFMetrics.log) just in case

**Comment by fifonik** [comment]
Duplicate, see #59 (some recommendations are there).
Unfortunately, I'm unable re-produce it and everything works fine with gyan's build on systems I tried.

**Comment by fifonik** [comment]
BTW, I released version 0.9.9 with increased timeouts and this should help with the issue. You can download and try it.
