### ISSUE TITLE
[Bug] "Add files" is disabled (0.9.9b)

### ISSUE THREAD

**Issue by fu-hsi** [fifonik/FFMetrics#64]
After choosing reference file, "Add files" is still disabled (drag & drop works).
In previous version this button was always enabled.

**Comment by fifonik** [comment]
Thanks.
I've updated archive and it should be fixed.

**Comment by fifonik** [comment]
Have you got chance to check if the issue is resolved?

**Comment by fu-hsi** [comment]
Problem solved.
