### ISSUE TITLE
CSV output doesn't appear to have any commas

### ISSUE THREAD

**Issue by ShortyCM** [fifonik/FFMetrics#66]
Since there is a 12-file limitation and I have 60 files to process today I have started loading up the 12 that will fit in the project and selected to output the CSV data files so that I can compare them all later.  However, the CSV output files don't appear to actually have any commas in them, so the data is not arranged in a fashion that's easily digested.  When I load up a CSV file in Excel this is what I see in one of the cells, which appears to be a large number of data entries that should have had commas to separate them, but instead they are all in one cell.  The data seems largely unreadable to me due to the lack of proper formatting.

1	5.607279	10.126511	0.996095	0.980712	0.988913	0.997662	0.999687	0.889344	0.995094	0.998022	0.998976	100	1

**Comment by fifonik** [comment]
As per the project home page, data saved as [tab-delimited csv](https://en.wikipedia.org/wiki/Tab-separated_values) so tabs are used as separators.
It can be imported in Excel with no issues.
