### ISSUE TITLE
Support photos

### ISSUE THREAD

**Issue by ss8688** [fifonik/FFMetrics#67]
Make calculating photos visual quality metrics possible.

**Comment by fifonik** [comment]
Sorry, but I'm only interested in video comparison.

**Comment by fifonik** [comment]
I've made tiny changes so jpg & png can be added into the program and published it as 1.3.1 beta 2. Feel free to download & check it out.

Note: still images comparison is out of scope of the program and I'm not going to check it. So this might be broken any time in future, sorry.

**Comment by fifonik** [comment]
This is strange, I uploaded it.
However, the zip was displayed for me with exclamation mark and message "Try to upload it again".
I've just re-uploaded it.
