### ISSUE TITLE
[Feature] Ability to set custom number of n_threads

### ISSUE THREAD

**Issue by rikinp93** [fifonik/FFMetrics#69]
Currently the tool has no ability to change the number of threads on the workflow. 

`n_threads={{n_threads}}`

It would be useful to adjust the number of threads as we currently use 38 threads in our workflow on a dedicated server for analysis. There shouldnt be a limitation of the value set.

**Comment by fifonik** [comment]
I do not really understand what you'd like to have.
You provided a part of FFMetrics.conf that is used by program. the {{n_threads}} is substituted runtime with a number of logical processors on the system minus 1. So on ly 16 core system it will becodem n_threads=15. On your 38 core system it should become n_threads=37. You can check it -- tick Options | Write FFMPeg commands into log, calculate VMAF and then check FFMetrics.log

IF for some reason you'd like to set the value manually -- just put the number you like in the config file:
`n_threads={{n_threads}}`
=>
`n_threads=42`

**Comment by fifonik** [comment]
I'm closing it as I do not understand what you'd like to have and no details provided.

**Comment by glazarov-uk** [comment]
Apologies for the delay we were out of office.  
Didn't know that setting the value manually in that config file is possible, thanks for clarifying.
