### ISSUE TITLE
Option to assign cores to vmaf calculations?

### ISSUE THREAD

**Issue by ls-milkyway** [fifonik/FFMetrics#76]
Nice app! ......specially the generation of graphs ....makes FFMetrics unique .....to increase VMAF calculation speed I could not find an option to assign CPU cores ....adding `n_threads=12` is all that you need to include in the [ffmpeg command as stated here.](https://github.com/Netflix/vmaf/issues/770)

**Comment by fifonik** [comment]
If you check the log after calculating VMAF metric using FFMetrics you should notice that n_threads is already in use.
Currently, the program should put there a value that equal "a number of logical CPUs found in the system minus 1".
This should be the best possible option in most cases.

You can also check #69
