### ISSUE TITLE
Allow to specify escaping characters for FFMpeg command line parameters in FFMetrics.conf

### ISSUE THREAD

**Issue by fifonik** [fifonik/FFMetrics#84]
To be used for escaping colon if default does not work correctly, for example: https://github.com/fifonik/FFMetrics/issues/81#issuecomment-1111499208

**Comment by fifonik** [comment]
Implemented in 1.2.1 beta 1

**Comment by ls-milkyway** [comment]
> Do you have any ideas how I can try to guess based on "configuration" ffmpeg returned how the executable was buid?
So, if I detect that it was build on windows, I can escape colon in filespec with triple back slashes, while when it was build on *nix -- single backslash.
Just curious, how gyan is building it? It shows "Build by MSYS2 project" as for your build.

I guess that you need to run `ffmpeg -version` or `ffmpeg -buildconf` and grab the output....here is an example explaining [details of a version switch](https://superuser.com/questions/1485855/why-does-ffmpeg-exe-version-not-give-simple-version-of-software-windows-10-6).

But, to simplify things ...& make ffmetrics more robust & efficient ...it would better (as I stated earlier) to find a working ffmpeg command using inbuilt model...valid for all types of releases: btbn, gyan, or custom... as it is the default & future proof update..& eliminates the need for model files in vmaf-models folder.

Yep, I am aware that gyan is also using gcc with MSYS2 .....but the difference is: I am using latest ffmpeg master git with last commit and other gits with latest patches.....plus he is using --enable-version3 switch ....I am still trying to find out differences ....and getting close to using his parameters without compromising on latest git versions/patches....till now the only feasible reason : [my builds are using msys2's bash environment](https://github.com/Netflix/vmaf/blob/0298e4f701c7363ed8d0592efbb728776fd068f5/resource/doc/ffmpeg.md#note-about-the-model-path-on-windows) ....thereby forcing me to use `\\\` & he is somehow using other environment ...may be powershell or cmd......I need some time to dig out the real reason.
