### ISSUE TITLE
[Enhancement] INI file for easy options selections

### ISSUE THREAD

**Issue by ls-milkyway** [fifonik/FFMetrics#94]
It will be easy for non-techie users if [you put an .ini or conf file with proper comments ](https://en.wikipedia.org/wiki/INI_file)for FFmetrics ....to override default options with user options in ffmetrics...check an ini file example below... thanks.

`[Metrics]`
` ;Select the metrics you wish to calculate`
`psnr = yes`
`ssim = no`
`ms-ssim = yes`
`vmaf = yes`

**Comment by fifonik** [comment]
I'd say we have 2 different things here:
1. To support .ini
2. To have config for some tasks

Unfortunately, I will not support ini format. The program already using json format for config/project files and for me as a developer this format is much more comfortable to work with.

As for ability to have "something configured", I need to understand exact issues you have.
Program is already use configuration file where you can change quite a lot related to how it works (and re-define parameters it supply to ffmpeg).
Also, program supports "projects", so you can add ref/distorted, specify metrics you'd like to calculate, define options and save everything as json file (in menu or Ctrl+Shift+S). Then you can re-load it when needed (menu or Ctrl+Shift+O).
The project will be loaded automatically on program restart (or you can specify "default template" project where you can have the metrics you like ticked and skip/duration specified and use it when starting a new project).
Let me know if you miss anything in current implementation. 
I will think about possible improvements.

**Comment by ls-milkyway** [comment]
> The program already using json format for config/project files and for me as a developer this format is much more comfortable to work with.
> 
> As for ability to have "something configured", I need to understand exact issues you have. Program is already use configuration file where you can change quite a lot related to how it works (and re-define parameters it supply to ffmpeg). Also, program supports "projects", so you can add ref/distorted, specify metrics you'd like to calculate, define options and save everything as json file (in menu or Ctrl+Shift+S). Then you can re-load it when needed (menu or Ctrl+Shift+O).

Ok...you can stick to JSON ...but put examples with comments there.....to facilitate easy changes for the casual users. 
for eg. If I  have ffmpeg compiled with DSSIM ...then it should be like putting DSSIM instead of SSIM OR even better if I just need to uncomment a line containing DSSIM .....hence put all lines with all possible quality metrics & ....all that users need is to just remove the comment from the line....to calculate the required parameter.

Example
`{
   "_VMAF": "Quality Metric 1",
   "_SSIM": "Quality Metric 2",
   "_MS-SSIM": "Quality Metric 3",
   "_DSSIM": "Quality Metric 4",
   "_PSNR": "Quality Metric 5"
}`

Remove "_" for needed metrics
