### ISSUE TITLE
[Feature] Add "analyze bitrate" as an option

### ISSUE THREAD

**Issue by lextra2** [fifonik/FFMetrics#97]
Something like this
![2420572-05](https://user-images.githubusercontent.com/20690384/183528056-d58673c4-e471-4aa1-b189-79d254eace5e.png)

**Comment by fifonik** [comment]
Not sure if this is related to metric. And I do not know if this can be done with ffmpeg.
I'm personally use Bitrate Viewer program for this:
![image](https://user-images.githubusercontent.com/7234987/183586116-b6669749-5304-4f73-b20f-9d3014cd1f03.png)

**Comment by lextra2** [comment]
>Not sure if this is related to metric

It is
>And I do not know if this can be done with ffmpeg

Me neither. But I figured by now there was a way. Oh well.

>I'm personally use Bitrate Viewer program for this

Yep. I know about that program. But I think it only supports h264.

**Comment by teb** [comment]
I love bitrateviewer, but theres no development here unfortunatly. Something like the same functionality would be great!

**Comment by fifonik** [comment]
I've just released another program with similar UI -- [FFBitrateViewer](https://github.com/fifonik/FFBitrateViewer).
Unfortunately, I do not have plans to in-build this functionality into FFMetrics.
