### ISSUE TITLE
FFMetrics Increase Score Sorting

### ISSUE THREAD

**Issue by henanzheng** [fifonik/FFMetrics#98]
FFMetrics is very convenient to use. Thanks for @ fifonik's contribution!

It would be better if the score sorting function was added. Like the computer resource manager, click the descending or ascending header.

![20220914024124](https://user-images.githubusercontent.com/111262981/189985737-8578c9cc-3066-4345-922f-1c720cb26d5b.png)

**Comment by fifonik** [comment]
Thanks for suggestion.
The feature is implemented in 1.4.6 beta 1.
It would be nice if you check it out.

**Comment by henanzheng** [comment]
Thanks, it's convenient now.
