### ISSUE TITLE
Bug: result file doesn't saves when run from command line

### ISSUE THREAD

**Issue by iPaltus** [fifonik/FFMetrics#99]
Please fix.
Result file doesn't saves when run from command line.
FFMetrics.exe -log-level=debug -run -duration=5 -skip=0 -save-results -save-results-file=c:\temp\result.csv c:\temp\kate.mp4 c:\temp\kate_av1_cpu3_q40.mp4

Files permissions ok, writing alowed. Logfile have nothing about result file. Results file saves correctrly when run manually from GUI.

**Comment by fifonik** [comment]
Sorry for late reply.
In the most recent version some options changed and you should use `-auto-save-results` and `-auto-save-results-file=...`

**Comment by iPaltus** [comment]
Thank you, it works!
Здорово, что файл результата не переписывается, а дополняется новыми результатами в отдельных строчках - можно считать метрики для новых файлов и натравить Excel на анализ из единого пополняемого файла.
